FROM debian:12
ENV TZ=Europe/Berlin
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/nim-2.2.10/bin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
 && apt-get update && apt-get install -y \
 git \
 gcc-12 \
 gcc \
 xz-utils \
 libpcre3 \
 wget \
 make \
 libsdl2-dev \
 libsdl2-image-dev \
 && wget https://nim-lang.org/download/nim-2.2.10-linux_x64.tar.xz \
 && tar -xf nim-2.2.10-linux_x64.tar.xz \
 && rm nim-2.2.10-linux_x64.tar.xz \
 && nimble install -y unittest2 "nimalyzer@#head" contracts \
 && wget https://github.com/libsdl-org/SDL/releases/download/release-2.32.10/SDL2-2.32.10.tar.gz \
 && tar -xf SDL2-2.32.10.tar.gz \
 && cd SDL2-2.32.10 \
 && ./configure --prefix=/usr \
 && make \
 && make install \
 && rm SDL2-2.32.10.tar.gz \
 && apt-get purge -y \
 wget \
 make \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
