FROM debian:12
ENV TZ=Europe/Berlin
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/nim-2.2.10/bin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
 && apt-get update && apt-get install -y \
 wget \
 gcc-12 \
 gcc \
 git \
 zip \
 unzip \
 binutils \
 gcc-mingw-w64-x86-64 \
 libpcre3 \
 xz-utils \
 make \
 libsdl2-dev \
 libsdl2-image-dev \
 && wget https://nim-lang.org/download/nim-2.2.10-linux_x64.tar.xz \
 && tar -xf nim-2.2.10-linux_x64.tar.xz \
 && rm nim-2.2.10-linux_x64.tar.xz \
 && nimble install -y "nimalyzer@#head" contracts \
 && wget https://github.com/libsdl-org/SDL/releases/download/release-2.32.10/SDL2-devel-2.32.10-mingw.tar.gz \
 && tar -xf SDL2-devel-2.32.10-mingw.tar.gz \
 && cd SDL2-2.32.10 \
 && make cross \
 && cd .. \
 && rm SDL2-devel-2.32.10-mingw.tar.gz \
 && rm -rf SDL2-2.32.10 \
 && wget https://github.com/libsdl-org/SDL_image/releases/download/release-2.8.12/SDL2_image-devel-2.8.12-mingw.tar.gz \
 && tar -xf SDL2_image-devel-2.8.12-mingw.tar.gz \
 && cd SDL2_image-2.8.12 \
 && make cross\
 && cd .. \
 && rm SDL2_image-devel-2.8.12-mingw.tar.gz \
 && rm -rf SDL2_image-2.8.12 \
 && wget https://github.com/libsdl-org/SDL/releases/download/release-2.32.10/SDL2-2.32.10-win32-x64.zip \
 && unzip -d /opt/SDL SDL2-2.32.10-win32-x64.zip \
 && rm SDL2-2.32.10-win32-x64.zip \
 && wget https://github.com/libsdl-org/SDL_image/releases/download/release-2.8.12/SDL2_image-2.8.12-win32-x64.zip \
 && unzip -o -d /opt/SDL SDL2_image-2.8.12-win32-x64.zip \
 && rm SDL2_image-2.8.12-win32-x64.zip \
 && apt-get purge -y \
 wget \
 unzip \
 make \
 && apt-get autoremove -y && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
